### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by YQjiuhao** [ZClee128/better_socket#11]
设备：simulator iPhone 11 Pro Max.
版本：better_socket: ^1.1.4
flutter版本：1.17.1
XCode 版本： 11.4.1

Command CompileSwift failed with a nonzero exit code
    /usr/local/lib/flutter/.pub-cache/hosted/pub.flutter-io.cn/better_socket-1.1.4/ios/Classes/BetterSocketPlugin.m:2:9:
    error: 'SRWebSocket.h' file not found with <angled> include; use "quotes" instead
    #import <SRWebSocket.h>
            ^~~~~~~~~~~~~~~
            "SRWebSocket.h"
    /usr/local/lib/flutter/.pub-cache/hosted/pub.flutter-io.cn/better_socket-1.1.4/ios/Classes/BetterSocketPlugin.m:32:1
    9: warning: unused variable 'keyStorePath' [-Wunused-variable]
            NSString *keyStorePath = dict[@"keyStorePath"];
                      ^
    /usr/local/lib/flutter/.pub-cache/hosted/pub.flutter-io.cn/better_socket-1.1.4/ios/Classes/BetterSocketPlugin.m:33:1
    9: warning: unused variable 'keyPassword' [-Wunused-variable]
            NSString *keyPassword = dict[@"keyPassword"];
                      ^
    /usr/local/lib/flutter/.pub-cache/hosted/pub.flutter-io.cn/better_socket-1.1.4/ios/Classes/BetterSocketPlugin.m:34:1
    9: warning: unused variable 'storePassword' [-Wunused-variable]
            NSString *storePassword = dict[@"storePassword"];
                      ^
    /usr/local/lib/flutter/.pub-cache/hosted/pub.flutter-io.cn/better_socket-1.1.4/ios/Classes/BetterSocketPlugin.m:35:1
    9: warning: unused variable 'keyStoreType' [-Wunused-variable]
            NSString *keyStoreType = dict[@"keyStoreType"];
                      ^
    4 warnings and 1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.

**Comment by pppshiwen** [comment]
same quetion

**Comment by ZClee128** [comment]
遇到这个问题，可以尝试手动pod install，因为我这边没测出来问题，所以不知道是哪个影响了，所以手动pod install把文件路径补全就可以

**Comment by zhubinsheng** [comment]
> 遇到这个问题，可以尝试手动pod install，因为我这边没测出来问题，所以不知道是哪个影响了，所以手动pod install把文件路径补全就可以

 这似乎并不起作用

**Comment by zhubinsheng** [comment]
https://www.cnblogs.com/ZhYQ-Note/p/5912827.html
用于标准库或框架头，并且搜索策略与用于,所以这样修改如下：
#import "SRWebSocket.h"

**Comment by YQjiuhao** [comment]
> > 遇到这个问题，可以尝试手动pod install，因为我这边没测出来问题，所以不知道是哪个影响了，所以手动pod install把文件路径补全就可以
> 
> 这似乎并不起作用

在Podfile.h文件顶部加入：source 'https://github.com/CocoaPods/Specs.git'，再pod install试试

**Comment by YQjiuhao** [comment]
> https://www.cnblogs.com/ZhYQ-Note/p/5912827.html
> 用于标准库或框架头，并且搜索策略与用于,所以这样修改如下：
> #import "SRWebSocket.h"

这样也行，但是在升级包的时候需要重新更改很麻烦

**Comment by happiness9721** [comment]
#import <SocketRocket/SRWebSocket.h>

遇到一樣的問題，我在本機改成這樣就編譯過了
