### ISSUE TITLE
How to make ping/pong with websocket server?

### ISSUE THREAD

**Issue by maxrks** [ZClee128/better_socket#16]
Thanks for the better_socket working on wss.
Could you give suggestions on how to make ping/pong heatbeat checking with weboscket server?
I hope there be `linkState`, `autoconnect`, `enablePingPong`,`timeout` properties so that let it work instantly.

here is error from console.
```I/flutter ( 3698): {reason: The connection was closed because the other endpoint did not respond with a pong in time. For more information check: https://github.com/TooTallNate/Java-WebSocket/wiki/Lost-connection-detection, code: 1006, event: onClose, remote: false}```

**Comment by ZClee128** [comment]
参考demo
