### ISSUE TITLE
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by jacky-yanglei** [ZClee128/better_socket#3]
如何关闭 wss 的证书验证呢？

**Comment by ZClee128** [comment]
能提过测试wss的地址吗？没办法验证成不成功

**Comment by jacky-yanglei** [comment]
url:    wss://api.matrixone.io/coinsdata/api/MarketsList/

parmas: '{"market":"USDT","exchange":"BN"}'

**Comment by ZClee128** [comment]
这个地址不需要什么设置都可以连通呀，就是你的参数传过去一直报参数错误，这个需要传什么样的格式过去

**Comment by ZClee128** [comment]
我不知道你是要怎么关闭证书验证，但是我测试了你这个地址，不需要配置是可以直接连通和得到响应的
![image](https://user-images.githubusercontent.com/18162711/72122995-c9181400-339a-11ea-9a61-35123562e596.png)

**Comment by jacky-yanglei** [comment]
![VMEOI6PW4N}VEVS XZ9RN65](https://user-images.githubusercontent.com/17645850/72123337-e0a3cc80-339b-11ea-9ea8-7ef734131e81.png)
我这样的使用方式有问题？  它无法建立连接。

**Comment by jacky-yanglei** [comment]
错误的意思就是证书验证的不成功的意思

**Comment by ZClee128** [comment]
加下qq吧，方便一点，876231865
