### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method connentSocket on channel better_socket)

### ISSUE THREAD

**Issue by byteslaves** [ZClee128/better_socket#5]
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method connentSocket on channel better_socket)
按照你的方法使用会出现这个问题

**Comment by ZClee128** [comment]
请clean一下项目，然后运行

**Comment by byteslaves** [comment]
> 请clean一下项目，然后运行

好的，谢谢
