### ISSUE TITLE
Not working on iOS simulator

### ISSUE THREAD

**Issue by crizant** [ZClee128/better_socket#6]
Hi, I have a problem when try to run `flutter run` on iOS simulator,
here is the full error log:

```
Launching lib/main.dart on iPhone 11 Pro in debug mode...
Running pod install...                                              1.4s
Running Xcode build...

Xcode build done.                                            3.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:489:34: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
            CFHTTPMessageAppendBytes(_receivedHTTPHeaders, (const UInt8 *)data.bytes, data.length);
                                     ^
                                     self->
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:491:43: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
            if (CFHTTPMessageIsHeaderComplete(_receivedHTTPHeaders)) {
                                              ^
                                              self->
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:492:106: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
                SRFastLog(@"Finished reading headers %@", CFBridgingRelease(CFHTTPMessageCopyAllHeaderFields(_receivedHTTPHeaders)));
                                                                                                             ^
                                                                                                             self->
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:509:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
        SecRandomCopyBytes(kSecRandomDefault, keyBytes.length, keyBytes.mutableBytes);
        ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:629:13: warning: 4 enumeration values not handled in switch: 'NSURLNetworkServiceTypeResponsiveData',
    'NSURLNetworkServiceTypeAVStreaming', 'NSURLNetworkServiceTypeResponsiveAV'... [-Wswitch]
        switch (requestNetworkServiceType) {
                ^
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:629:13: note: add missing switch cases
        switch (requestNetworkServiceType) {
                ^
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:746:24: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
            dispatch_async(_workQueue, ^{
                           ^
                           self->
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:756:13: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
                _failed = YES;
                ^
                self->
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:816:24: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
            dispatch_async(_workQueue, ^{
                           ^
                           self->
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1100:60: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
            size_t extra_bytes_needed = header.masked ? sizeof(_currentReadMaskKey) : 0;
                                                               ^
                                                               self->
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1131:50: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
                        assert(mapped_size >= sizeof(_currentReadMaskOffset) + offset);
                                                     ^
                                                     self->
    In module 'Foundation' imported from /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.h:17:
    In module 'CoreFoundation' imported from
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
        (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                            ^
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1144:10: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
            [_currentFrameData setLength:0];
             ^
             self->
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1146:9: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
            _currentFrameOpcode = 0;
            ^
            self->
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1147:9: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
            _currentFrameCount = 0;
            ^
            self->
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1148:9: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
            _readOpCount = 0;
            ^
            self->
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1149:9: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
            _currentStringScanPosition = 0;
            ^
            self->
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1195:68: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
                        [self.delegate webSocket:self didCloseWithCode:_closeCode reason:_closeReason wasClean:YES];
                                                                       ^
                                                                       self->
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1195:86: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
                        [self.delegate webSocket:self didCloseWithCode:_closeCode reason:_closeReason wasClean:YES];
                                                                                         ^
                                                                                         self->
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1257:9: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
            _selfRetain = nil;
            ^
            self->
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1485:9: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
            SecRandomCopyBytes(kSecRandomDefault, sizeof(uint32_t), (uint8_t *)mask_key);
            ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1589:30: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
                            if (!_sentClose && !_failed) {
                                 ^
                                 self->
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1589:45: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
                            if (!_sentClose && !_failed) {
                                                ^
                                                self->
    /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1590:29: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
    [-Wimplicit-retain-self]
                                _sentClose = YES;
                                ^
                                self->
    22 warnings generated.
    /Users/crizant/.pub-cache/hosted/pub.dartlang.org/better_socket-1.1.3/ios/Classes/BetterSocketPlugin.m:32:19: warning: unused variable 'keyStorePath' [-Wunused-variable]
            NSString *keyStorePath = dict[@"keyStorePath"];
                      ^
    /Users/crizant/.pub-cache/hosted/pub.dartlang.org/better_socket-1.1.3/ios/Classes/BetterSocketPlugin.m:33:19: warning: unused variable 'keyPassword' [-Wunused-variable]
            NSString *keyPassword = dict[@"keyPassword"];
                      ^
    /Users/crizant/.pub-cache/hosted/pub.dartlang.org/better_socket-1.1.3/ios/Classes/BetterSocketPlugin.m:34:19: warning: unused variable 'storePassword' [-Wunused-variable]
            NSString *storePassword = dict[@"storePassword"];
                      ^
    /Users/crizant/.pub-cache/hosted/pub.dartlang.org/better_socket-1.1.3/ios/Classes/BetterSocketPlugin.m:35:19: warning: unused variable 'keyStoreType' [-Wunused-variable]
            NSString *keyStoreType = dict[@"keyStoreType"];
                      ^
    4 warnings and 1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro.
```

**Comment by ZClee128** [comment]
It shouldn't be a problem with the simulator. It's a problem with your method of use. You can paste the code to see it, or refer to the following example code. I have no problem running in the simulator

**Comment by zhubinsheng** [comment]
> 嗨，我在尝试`flutter run`在iOS模拟器上运行时遇到问题，
> 这是完整的错误日志：
> 
> ```
> Launching lib/main.dart on iPhone 11 Pro in debug mode...
> Running pod install...                                              1.4s
> Running Xcode build...
> 
> Xcode build done.                                            3.0s
> Failed to build iOS app
> Error output from Xcode build:
> ↳
>     ** BUILD FAILED **
> 
> 
> Xcode's output:
> ↳
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:489:34: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>             CFHTTPMessageAppendBytes(_receivedHTTPHeaders, (const UInt8 *)data.bytes, data.length);
>                                      ^
>                                      self->
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:491:43: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>             if (CFHTTPMessageIsHeaderComplete(_receivedHTTPHeaders)) {
>                                               ^
>                                               self->
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:492:106: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>                 SRFastLog(@"Finished reading headers %@", CFBridgingRelease(CFHTTPMessageCopyAllHeaderFields(_receivedHTTPHeaders)));
>                                                                                                              ^
>                                                                                                              self->
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:509:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
>         SecRandomCopyBytes(kSecRandomDefault, keyBytes.length, keyBytes.mutableBytes);
>         ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:629:13: warning: 4 enumeration values not handled in switch: 'NSURLNetworkServiceTypeResponsiveData',
>     'NSURLNetworkServiceTypeAVStreaming', 'NSURLNetworkServiceTypeResponsiveAV'... [-Wswitch]
>         switch (requestNetworkServiceType) {
>                 ^
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:629:13: note: add missing switch cases
>         switch (requestNetworkServiceType) {
>                 ^
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:746:24: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>             dispatch_async(_workQueue, ^{
>                            ^
>                            self->
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:756:13: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>                 _failed = YES;
>                 ^
>                 self->
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:816:24: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>             dispatch_async(_workQueue, ^{
>                            ^
>                            self->
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1100:60: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>             size_t extra_bytes_needed = header.masked ? sizeof(_currentReadMaskKey) : 0;
>                                                                ^
>                                                                self->
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1131:50: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>                         assert(mapped_size >= sizeof(_currentReadMaskOffset) + offset);
>                                                      ^
>                                                      self->
>     In module 'Foundation' imported from /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.h:17:
>     In module 'CoreFoundation' imported from
>     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
>     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
>         (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
>                             ^
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1144:10: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>             [_currentFrameData setLength:0];
>              ^
>              self->
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1146:9: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>             _currentFrameOpcode = 0;
>             ^
>             self->
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1147:9: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>             _currentFrameCount = 0;
>             ^
>             self->
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1148:9: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>             _readOpCount = 0;
>             ^
>             self->
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1149:9: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>             _currentStringScanPosition = 0;
>             ^
>             self->
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1195:68: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>                         [self.delegate webSocket:self didCloseWithCode:_closeCode reason:_closeReason wasClean:YES];
>                                                                        ^
>                                                                        self->
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1195:86: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>                         [self.delegate webSocket:self didCloseWithCode:_closeCode reason:_closeReason wasClean:YES];
>                                                                                          ^
>                                                                                          self->
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1257:9: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>             _selfRetain = nil;
>             ^
>             self->
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1485:9: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
>             SecRandomCopyBytes(kSecRandomDefault, sizeof(uint32_t), (uint8_t *)mask_key);
>             ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1589:30: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>                             if (!_sentClose && !_failed) {
>                                  ^
>                                  self->
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1589:45: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>                             if (!_sentClose && !_failed) {
>                                                 ^
>                                                 self->
>     /Users/crizant/Documents/web_socket_test/ios/Pods/SocketRocket/SocketRocket/SRWebSocket.m:1590:29: warning: block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior
>     [-Wimplicit-retain-self]
>                                 _sentClose = YES;
>                                 ^
>                                 self->
>     22 warnings generated.
>     /Users/crizant/.pub-cache/hosted/pub.dartlang.org/better_socket-1.1.3/ios/Classes/BetterSocketPlugin.m:32:19: warning: unused variable 'keyStorePath' [-Wunused-variable]
>             NSString *keyStorePath = dict[@"keyStorePath"];
>                       ^
>     /Users/crizant/.pub-cache/hosted/pub.dartlang.org/better_socket-1.1.3/ios/Classes/BetterSocketPlugin.m:33:19: warning: unused variable 'keyPassword' [-Wunused-variable]
>             NSString *keyPassword = dict[@"keyPassword"];
>                       ^
>     /Users/crizant/.pub-cache/hosted/pub.dartlang.org/better_socket-1.1.3/ios/Classes/BetterSocketPlugin.m:34:19: warning: unused variable 'storePassword' [-Wunused-variable]
>             NSString *storePassword = dict[@"storePassword"];
>                       ^
>     /Users/crizant/.pub-cache/hosted/pub.dartlang.org/better_socket-1.1.3/ios/Classes/BetterSocketPlugin.m:35:19: warning: unused variable 'keyStoreType' [-Wunused-variable]
>             NSString *keyStoreType = dict[@"keyStoreType"];
>                       ^
>     4 warnings and 1 error generated.
>     note: Using new build system
>     note: Planning build
>     note: Constructing build description
> 
> Could not build the application for the simulator.
> Error launching application on iPhone 11 Pro.
> ```

请问这个问题是如何解决的最后？感谢你的指导

**Comment by crizant** [comment]
@zhubinsheng I did't solve this problem, I used another library instead.

**Comment by zhubinsheng** [comment]
> @zhubinsheng I did't solve this problem, I used another library instead.

I encountered this problem a few months ago and modified it. Today, I cleaned all the pub files, causing this problem to recur. I can't remember how to solve it for a while
