### ISSUE TITLE
pub get 出错

### ISSUE THREAD

**Issue by lubaoyilang** [ZClee128/better_socket#8]
首先，这个库非常nice

flutter packages get
Running "flutter pub get" in pkha...                            
Because pkha depends on better_socket ^1.1.4 which doesn't match any versions, version solving failed.
pub get failed (1; Because pkha depends on better_socket ^1.1.4 which doesn't match any versions, version solving failed.)
exit code 1

但是 1.13我可以用，1.14改动了什么吗？

**Comment by lubaoyilang** [comment]
我flutter用的 1.12.13 fix8

**Comment by ZClee128** [comment]
clean项目，然后再重新更新下就可以了
