### ISSUE TITLE
你好想请教一个问题如下

### ISSUE THREAD

**Issue by zhubinsheng** [ZClee128/better_socket#9]
byteArrayactions[0]=0x48;//H
byteArrayactions[1]=0x02;
byteArrayactions[2]=(byte)4;
byteArrayactions[3]=(byte)6;
byteArrayactions[4]=(byte)9;
这是我在java中写的代码，byte数组添加如上5个数组，刚入门flutter，希望大佬可以在百忙之中抽空为小弟解决下这个问题，如何在flutter中实现?
我已经知晓可以用Utf8Encoder().convert('HOPEN')这种方式来将字符串转化成Uint8List，
但是我不知道如何将字符串和int一起转化

**Comment by zhubinsheng** [comment]
import 'dart:convert';
import 'dart:typed_data';

void main() {
  var listString = Utf8Encoder().convert('HCC');
  var listInt = [111, 20, 33, 41, 25, 25, 25, 25, 25, 787,0x02,0x4F];
  var int2utf8 = Uint8List.fromList(listInt);
 
  var listall = listString+int2utf8;
  Uint8List last = Uint8List.fromList(listall);
  
  print(listall);
  print(last.elementAt(0));
  print(last.sublist(1));
}
你好，经过实验需要三次转化可以将字符串和ASCII和整形转化在一起成为字节型集合
在回转的过程中如最后两个打印，print(last.elementAt(0));可以打印字节型集合中的第一个的数值但是并不是字符串，但这对我足够了，谢谢

**Comment by ZClee128** [comment]
解决就好，最近项目忙，都没时间更新了
